# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'IAPDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IAPDemo
  pod 'wibmo-sdk', '~>3.0.1'

end

target 'IAPDemoObjc' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for IAPDemo
    pod 'wibmo-sdk', '~>3.0.1'    
end
